<div id="footer">
		<div>
			<p>&copy; 2016 by TailsWagz. All rights reserved.</p>
			<ul>
				<li>
					<a href="http://www.twitter.com/tailwagz" id="twitter">twitter</a>
				</li>
				<li>
					<a href="http://www.facebook.com/tailwagz" id="facebook">facebook</a>
				</li>
				<li>
					<a href="http://www.googleplus.com/tailwagz" id="googleplus">googleplus</a>
				</li>
				<li>
					<a href="http://www.pinterest.com/tailwagz" id="pinterest">pinterest</a>
				</li>
			</ul>
		</div>
</div>