<div id="header">
		<div id="authBanner">			
		<?php
			display_session_username();
			display_session_actions();				
		?></div>
		<a id="imageBanner" href="index.php" class="logo">
			<img src="images/logo.png" alt="TailWagz logo">
		</a>
		<ul id="navigationBanner">
			<li>
				<a href="index.php">home</a>
			</li>
			<li>
				<a href="results.php">browse</a>
			</li>
			<li>
				<a href="search.php">search</a>
			</li>
		</ul>
	</div>