<div id="header">
		<a href="index.html" class="logo">
			<img src="images/logo.jpg" alt="">
		</a>
		<ul id="navigation">
			<li class="selected">
				<a href="index.php">home</a>
			</li>
			<li>
				<a href="search.php">search</a>
			</li>
			<li>
				<a href="browse.php">browse</a>
			</li>
			<li>
				<a href="signup.php">sign up</a>
			</li>
			<li>
				<a href="results.php">results</a>
			</li>
			<li>
				<a href="item.php">single item</a>
			</li>
			
		</ul>
	</div>